### ISSUE TITLE
Where is the ffmpeg builder itself?

### ISSUE THREAD

**Issue by coolaj86** [Zeranoe/ffmpeg-builds-page#10]
I see that the site hosting the Windows builds is going down soon.

Do you have the build scripts and such for that available?

**Comment by Zeranoe** [comment]
> Where is the ffmpeg builder itself?

This repo is for the "page", not the builds.

> Do you have the build scripts and such for that available?

The build scripts for FFmpeg and libraries is not available, as their quality is poor.
