### ISSUE TITLE
Support GSM 6.10 Encoder/Decoder for Windows

### ISSUE THREAD

**Issue by heretic13** [Zeranoe/ffmpeg-builds-page#6]
Hello.

Could you add support for GSM 6.10 decoder / encoder to the Windows build?

Linux has it (Ubuntu 20.04).

I am doing cross-platform software using ffmpeg that transcodes and resamples audio. At the moment, I am concerned about the lack of support for the GSM codec in the "official" Windows assembly of ffmpeg.

I would not like to conditionally compile my project for the sake of one codec, depending on whether ffmpeg supports the GSM codec or not.

Building ffmpeg itself according to the documentation is too time-consuming, while there is an “official” build.

**Comment by Zeranoe** [comment]
GSM support has been added with 20200620-29ea4e1
